/**
 * Generates `PLATFORM-LIMITS.md`: what each store lets Agentship do, and what it does not.
 *
 * Written from the capability maps of both adapters and from the console catalog, because
 * a hand-written version of this table would be wrong within one release — and a table that
 * is wrong about what needs a human is exactly the kind of documentation that gets someone
 * to promise an agent can do something it must not.
 *
 * Run with: pnpm generate:platform-limits
 */
import { writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { APPLE_CAPABILITIES } from '../packages/adapter-apple/src/index.js';
import { GOOGLE_CAPABILITIES } from '../packages/adapter-google/src/index.js';
import { type CatalogEntryWithStore, catalogEntries } from '../packages/catalog/src/index.js';
import { type ActionClass, OPERATION_IDS, type Store } from '../packages/core/src/index.js';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export const PLATFORM_LIMITS_PATH = resolve(REPO_ROOT, 'PLATFORM-LIMITS.md');

const GENERATED_NOTE =
  '<!-- Generated by scripts/generate-platform-limits.ts from the adapter capability maps and the console catalog. Do not edit by hand. -->';

/** What a user reads in the table, per capability class. */
const CELL: Record<string, string> = {
  auto: 'API',
  needs_approval: 'API (you approve)',
  needs_input: 'API (needs a value)',
  agent_browser: 'Console',
  human_only: 'Console (you)',
  unsupported: '—',
};

const OPERATION_LABEL: Record<(typeof OPERATION_IDS)[number], string> = {
  checkAuth: 'Check the credentials work',
  listApps: 'List the apps the credentials can see',
  getAppState: 'Read the state of the app',
  listProducts: 'List in-app products and subscriptions',
  getProductState: 'Read one product: prices, offers, availability',
  getSubmissionStatus: 'Read the state of a review submission',
  buildArtifact: 'Compile and sign the app on this machine',
  ensureVersion: 'Create or reuse the editable version',
  releaseVersion: 'Release an approved version the store is holding',
  setMetadata: 'Write listing text (name, description, what is new)',
  syncScreenshots: 'Upload and prune store images',
  uploadBuild: 'Upload the build (.ipa / .aab)',
  distributeToTesters: 'Give a build to testers',
  manageTesterGroups: 'Create tester groups and manage members',
  setPricing: 'Set the price of the app',
  submitForReview: 'Submit for review / roll out',
  setPhasedRelease: 'Phased release / staged rollout',
  createProduct: 'Create an in-app product or subscription',
  updateProduct: 'Change a product’s name, period or localizations',
  setProductPricing: 'Price a product in each territory',
  setProductOffers: 'Introductory and promotional offers',
  createApp: 'Create the app record itself',
  firstRelease: 'Perform the very first release',
  privacyLabels: 'Declare Apple App Privacy',
  dataSafety: 'Declare Google Play Data Safety',
  contentRating: 'Answer the content rating questionnaire',
  appPricing: 'Set up the pricing model of the app',
  appAvailability: 'Choose the countries the app is sold in',
  appContentDeclarations: 'Answer the app content declarations',
  playAppSigning: 'Configure Play App Signing',
  resolutionCenter: 'Reply to the review team',
  reviewStatus: 'Read a detailed review status',
  agreementsTaxBanking: 'Accept agreements, set up tax and banking',
};

const CATEGORY_TITLE: Record<string, string> = {
  account: 'Account and enrollment',
  app_record: 'The app record',
  agreements: 'Agreements, tax and banking',
  pricing: 'Pricing and availability',
  privacy: 'Privacy declarations',
  content_rating: 'Content rating',
  availability: 'Availability',
  review: 'Review',
  monetization: 'Monetisation',
  credentials: 'Credentials',
  other: 'Other',
};

function consoleTable(entries: readonly CatalogEntryWithStore[]): string {
  const rows = entries.map((entry) => {
    const who = entry.class === 'human_only' ? 'You, personally' : 'You or your agent';
    const why =
      entry.class === 'human_only' ? `${entry.reason} ${entry.humanReason}` : entry.reason;
    return `| ${entry.title} | \`${entry.id}\` | ${who} | ${why.replace(/\n/g, ' ')} | ${entry.lastVerified} |`;
  });
  return `| Operation | Id | Who does it | Why it cannot be an API call | Checked |\n|---|---|---|---|---|\n${rows.join('\n')}`;
}

function capabilityTable(): string {
  const rows = OPERATION_IDS.map((id) => {
    const apple = CELL[APPLE_CAPABILITIES[id] as ActionClass] ?? APPLE_CAPABILITIES[id];
    const google = CELL[GOOGLE_CAPABILITIES[id] as ActionClass] ?? GOOGLE_CAPABILITIES[id];
    return `| ${OPERATION_LABEL[id]} | ${apple} | ${google} |`;
  });
  return `| What you want | App Store | Google Play |\n|---|---|---|\n${rows.join('\n')}`;
}

function consoleSections(store: Store): string {
  const entries = catalogEntries(store);
  const categories = [...new Set(entries.map((entry) => entry.category))];
  return categories
    .map((category) => {
      const inCategory = entries.filter((entry) => entry.category === category);
      return `#### ${CATEGORY_TITLE[category] ?? category}\n\n${consoleTable(inCategory)}`;
    })
    .join('\n\n');
}

export function platformLimitsMarkdown(): string {
  const humanOnly = catalogEntries().filter((entry) => entry.class === 'human_only');
  return `# Platform limits

${GENERATED_NOTE}

Agentship automates everything the App Store Connect and Google Play APIs expose, and hands
back structured instructions for everything else. This page is the honest boundary between
the two, generated from the code that enforces it.

Read the columns as:

- **API** — Agentship does it for you.
- **API (you approve)** — Agentship does it, after you approve that exact change. Money,
  privacy, review submissions and anything reaching production always land here.
- **API (needs a value)** — Agentship needs something from you before it can act.
- **Console** — no API exists. Agentship gives your agent the exact page, steps and values;
  an agent with a browser may follow them after showing you what it will submit.
- **Console (you)** — no API exists *and* you must do it yourself: identity, money,
  agreements, two-factor. Never let an agent attempt these.
- **—** — the store has no such concept, or Agentship deliberately does not touch it.

## What each store lets Agentship do

${capabilityTable()}

## Work with no API

Every entry below is real console work, with the page it lives on and the date the
instructions were last checked against that page. Agentship proposes the values it already
knows and verifies the result afterwards where the store lets it be verified.

### App Store Connect

${consoleSections('apple')}

### Google Play

${consoleSections('google')}

## Things only you can do

${humanOnly
  .map((entry) => `- **${entry.title}** (${entry.store}) — ${entry.humanReason}`)
  .join('\n')}

## Two limits worth knowing before you start

- A new personal Google Play developer account must run a closed test with at least 12
  testers for 14 continuous days before it may publish to production. There is no way
  around it; plan for it.
- Apple issues the App Store Connect \`.p8\` key file exactly once. If it is lost, the key
  must be revoked and a new one generated.

## Platforms

Agentship runs on macOS and Linux, on x64 and arm64. Windows is not supported. Building an
\`.ipa\` requires macOS with Xcode; everything else — including the whole Google Play side
and every store operation for iOS — works anywhere, and a build produced elsewhere can be
published by pointing \`release.artifacts\` at the file.
`;
}

const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  await writeFile(PLATFORM_LIMITS_PATH, platformLimitsMarkdown());
  console.log(`wrote ${PLATFORM_LIMITS_PATH}`);
}
