/**
 * Generates the skill reference files that must not drift from the code.
 *
 * `stores.md` is the real coverage table of both adapters, and `errors.md` is the real
 * error catalog. Writing either by hand would guarantee that one day a skill tells an
 * agent something the engine stopped doing — so they are produced from
 * `CapabilityMap` and `ERROR_CODES`, and a test regenerates them to prove the checked-in
 * copies are current.
 *
 * Run with: pnpm generate:skill-references
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  APPLE_CAPABILITIES,
  APPLE_PENDING_OPERATIONS,
} from '../packages/adapter-apple/src/index.js';
import {
  GOOGLE_CAPABILITIES,
  GOOGLE_PENDING_OPERATIONS,
} from '../packages/adapter-google/src/index.js';
import {
  type AgentshipErrorCode,
  ERROR_CODES,
  errorFamily,
  OPERATION_IDS,
  type PendingOperation,
} from '../packages/core/src/index.js';

const SKILLS_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '../packages/cli/skills');

const GENERATED_NOTE =
  '<!-- Generated by scripts/generate-skill-references.ts from the adapters and the error catalog. Do not edit by hand. -->';

/** What each operation means in a sentence an agent can relay. */
const OPERATION_SUMMARIES: Record<(typeof OPERATION_IDS)[number], string> = {
  checkAuth: 'Prove the stored credentials work',
  listApps: 'List the apps the credentials can see',
  getAppState: 'Read the full state of one app',
  listProducts: 'List in-app products and subscriptions',
  getProductState: 'Read one product completely: prices per territory, offers, availability',
  getSubmissionStatus: 'Read the state of a review submission',
  buildArtifact: 'Compile and sign the app on this machine',
  ensureVersion: 'Create or reuse the editable store version',
  setMetadata: 'Write listing text (name, description, keywords, what is new)',
  syncScreenshots: 'Upload and prune store images',
  uploadBuild: 'Upload a build (.ipa / .aab)',
  distributeToTesters: 'Release a build to a tester group or track',
  manageTesterGroups: 'Create tester groups and manage members',
  setPricing: 'Set the price of the app',
  submitForReview: 'Submit a version for review',
  setPhasedRelease: 'Control phased release / staged rollout',
  releaseVersion: 'Release an approved version that the store is holding',
  createProduct: 'Create an in-app product or subscription',
  updateProduct: 'Change a product’s name, period or localizations',
  setProductPricing: 'Set a product’s price in each territory',
  setProductOffers: 'Create introductory or promotional offers',
  createApp: 'Create the app record itself',
  firstRelease: 'Perform the very first release of an app',
  privacyLabels: 'Declare Apple App Privacy labels',
  dataSafety: 'Declare the Google Play Data Safety form',
  contentRating: 'Answer the content rating questionnaire',
  appPricing: 'Set up the pricing model of the app',
  appAvailability: 'Choose the countries the app is available in',
  appContentDeclarations: 'Answer the app content declarations',
  playAppSigning: 'Configure Play App Signing',
  resolutionCenter: 'Reply to the review team',
  reviewStatus: 'Read a detailed review status',
  agreementsTaxBanking: 'Accept agreements and set up tax and banking',
};

const CLASS_MEANING: Record<string, string> = {
  auto: 'Agentship does it; nothing to ask.',
  needs_approval: 'Agentship can do it, but a human must approve the exact content first.',
  agent_browser:
    'No API. Agentship emits structured console instructions; an agent with a browser may follow them after showing the user what it will submit.',
  human_only:
    'No API, and a human must do it personally (identity, tax, banking, agreements, 2FA).',
  needs_input: 'A value is missing before anything can happen.',
  unsupported: 'Agentship will not do it by any means. Tell the user to do it in the console.',
};

function pendingSection(operations: readonly PendingOperation[]): string {
  return operations
    .map(
      (operation) =>
        `- **${operation.title}** (\`${operation.id}\`, ${operation.actionClass}) — ${operation.reason}${
          operation.console === undefined ? '' : ` Console: ${operation.console.url}`
        }`,
    )
    .join('\n');
}

function storesMarkdown(): string {
  const rows = OPERATION_IDS.map(
    (id) =>
      `| ${OPERATION_SUMMARIES[id]} | \`${id}\` | ${APPLE_CAPABILITIES[id]} | ${GOOGLE_CAPABILITIES[id]} |`,
  ).join('\n');

  return `# What the stores let Agentship do

${GENERATED_NOTE}

This is the real coverage table of both adapters. Use it to answer "can you do X?" honestly
before promising anything, and to know in advance which parts of a release will need the user.

| Operation | Id | Apple | Google |
|---|---|---|---|
${rows}

## What each classification means for you

${Object.entries(CLASS_MEANING)
  .map(([name, meaning]) => `- **${name}** — ${meaning}`)
  .join('\n')}

The classification in a plan can be stricter than this table: pricing, privacy declarations,
review submissions, destructive changes and anything reaching production are always
\`needs_approval\`, even where the store would allow Agentship to act alone.

## Console-only work known before any plan

### App Store Connect
${pendingSection(APPLE_PENDING_OPERATIONS)}

### Google Play
${pendingSection(GOOGLE_PENDING_OPERATIONS)}

## Two limits worth telling the user early

- A new personal Google Play account must run a closed test with at least 12 testers for 14
  continuous days before it can publish to production. It cannot be bypassed; plan for it.
- Apple issues the App Store Connect \`.p8\` key file exactly once. If it is lost, the key has
  to be revoked and a new one generated.
`;
}

/** One line per error code: what it means and what to do about it. */
const ERROR_GUIDANCE: Record<AgentshipErrorCode, string> = {
  AUTH_MISSING_CREDENTIALS:
    'No credentials for that store. Run agentship_configure_auth and walk the user through the console steps.',
  AUTH_INVALID_CREDENTIALS:
    'The stored credential is malformed. Ask the user to create a new key and store it again.',
  AUTH_KEYRING_UNAVAILABLE:
    'No OS keyring on this machine. Use the credential environment variables instead (agentship_setup_status lists them).',
  AUTH_KEYRING_ERROR: 'The keyring exists but refused the operation. Ask the user to unlock it.',
  AUTH_PROFILE_NOT_FOUND: 'The named credential profile does not exist. Use one that does.',
  AUTH_ENV_INCOMPLETE:
    'Some credential environment variables are set and others are missing. Set the whole group or none.',
  AUTH_PERMISSION_DENIED:
    'The credential works but lacks permissions. Apple: create the key with the App Manager role. Google: check the service account in Play Console Users and permissions.',
  TOOL_PLATFORM_UNSUPPORTED: 'Agentship supports macOS and Linux on x64 and arm64.',
  TOOL_UNKNOWN: 'Internal: a tool name Agentship does not manage.',
  TOOL_LOCK_ENTRY_MISSING: 'The pinned toolchain has no build for this platform.',
  TOOL_NOT_INSTALLED: 'Tell the user to run "agentship setup --yes".',
  TOOL_DOWNLOAD_FAILED:
    'Network problem while downloading a managed binary. Retry, then check connectivity.',
  TOOL_CHECKSUM_MISMATCH:
    'A downloaded binary did not match its pinned hash. Stop and report it: this is a supply-chain signal, not a retry.',
  TOOL_SIZE_EXCEEDED:
    'A download was larger than the pinned size. Same handling as a checksum mismatch.',
  TOOL_LOCK_TIMEOUT: 'Another Agentship process is installing. Wait and retry.',
  TOOL_HEALTHCHECK_FAILED:
    'A freshly installed binary did not run. Tell the user to run "agentship doctor".',
  TOOL_INSTALL_CORRUPT: 'The installation is damaged. "agentship doctor" repairs or reinstalls it.',
  TOOL_ROLLBACK_UNAVAILABLE: 'No previous version to roll back to. Run "agentship update --yes".',
  TOOL_EXEC_FAILED: 'A managed binary failed. Read the error detail; it carries the store message.',
  TOOL_TIMEOUT: 'A store call took too long. Retry; if it persists, check the store status page.',
  TOOL_OUTPUT_TOO_LARGE: 'A store answer was too large to process. Narrow the request.',
  TOOL_INVALID_OUTPUT:
    'A managed binary returned something unexpected. "agentship doctor", then report it.',
  TOOL_VERSION_DRIFT:
    'The installed binary is not the pinned version. Run "agentship update --yes".',
  BUILD_PLATFORM_UNSUPPORTED:
    'This machine cannot produce that artifact at all (an .ipa needs macOS). Build it elsewhere and point release.artifacts at the file; everything else Agentship does still works here.',
  BUILD_TOOL_MISSING:
    'A build tool the project needs is not installed (Xcode, a JDK, the Flutter SDK). The remediation names the exact one; Agentship does not install it for the user.',
  BUILD_UNSUPPORTED_PROJECT:
    'Agentship has no builder for this project shape — usually an Expo managed app with no ios/ or android/ folder. Never run "expo prebuild" for the user: it regenerates those folders and can overwrite native changes. Offer the two documented ways out.',
  BUILD_INPUT_REQUIRED:
    'The build needs a value the manifest does not have (a scheme, a build number). Ask the user for exactly the listed paths and write them into .agentship/agentship.yaml.',
  BUILD_FAILED:
    'The build tool failed. The error carries a diagnosis and the path of the full log; relay those. Never paste a build log into the conversation.',
  BUILD_SIGNING_FAILED:
    'Code signing failed. Read the remediation: it distinguishes a missing certificate, an unregistered bundle id, unaccepted agreements and a wrong keystore password, and each has a different fix.',
  BUILD_ARTIFACT_INVALID:
    'The build produced nothing, or something whose version contradicts the release. Do not upload it: align the manifest with the project, or stop hard-coding the version in the project.',
  STORE_UNAUTHORIZED:
    'The store rejected the credentials. Re-check them with agentship_setup_status.',
  STORE_NOT_FOUND:
    'The store does not have that resource. For a missing app record, the create-app pending operation is the way forward.',
  STORE_RATE_LIMITED: 'The store throttled us. Retryable: wait and try again.',
  STORE_UNAVAILABLE: 'The store is down or in maintenance. Retryable.',
  STORE_VALIDATION_FAILED:
    'The store rejected the content. Read the message, fix the manifest, plan again.',
  STORE_CONFLICT:
    'The remote state moved under us (a version already in review, an expired edit). Plan again and show the new diff.',
  STORE_UNSUPPORTED_OPERATION: 'No API for this. Continue through agentship_pending.',
  STORE_REJECTED: 'The store refused for policy reasons. Relay the message; do not retry blindly.',
  ANALYZE_PATH_NOT_FOUND: 'The path does not exist. Ask the user for the repository root.',
  ANALYZE_NOT_A_DIRECTORY: 'Pass the repository root, not a file.',
  ANALYZE_FRAMEWORK_UNKNOWN:
    'Agentship could not identify the framework. Ask the user what it is and fill the manifest by hand.',
  ANALYZE_LIMIT_EXCEEDED: 'The repository hit a scan limit. Results are partial; say so.',
  ANALYZE_UNREADABLE: 'The repository could not be read. Check permissions.',
  PLAN_APPROVAL_REQUIRED:
    'Show the diff to the user and pass the approved action id to agentship_apply.',
  PLAN_APPROVAL_STALE:
    'The content changed after the approval. Plan again, show the new diff, ask again. Never reuse the old id.',
  PLAN_INPUT_REQUIRED:
    'A manifest value is missing. Ask the user for exactly the listed paths and write them into .agentship/agentship.yaml.',
  PLAN_CONFLICT: 'The plan no longer matches the store. Plan again.',
  PLAN_JOURNAL_CORRUPT:
    'The journal is unreadable, so Agentship verifies against the store instead of trusting it. Nothing is executed blindly; call agentship_resume.',
  PLAN_NOT_FOUND: 'The plan id is not the current one. Call agentship_plan and use the new id.',
  PLAN_STEP_FAILED:
    'An action failed mid-run. Read the outcome, fix the cause, call agentship_resume.',
  PLAN_LOCKED:
    'Another apply is running for this project. Wait for it instead of forcing anything.',
  CONFIG_INVALID: 'Agentship configuration failed validation. The message names the file to fix.',
  CONFIG_NOT_FOUND:
    'Something Agentship needs does not exist yet — usually the manifest. Run agentship_analyze first.',
  CONFIG_HOME_UNWRITABLE:
    'Agentship cannot write to ~/.agentship. Check permissions or set AGENTSHIP_HOME.',
  CONFIG_MANIFEST_INVALID:
    '.agentship/agentship.yaml failed validation. The error details name the fields; fix them and plan again.',
  CONFIG_UNSUPPORTED_VERSION:
    'The file was written by a different Agentship. Run "agentship update --yes".',
};

function errorsMarkdown(): string {
  const families = new Map<string, string[]>();
  for (const code of Object.values(ERROR_CODES)) {
    const family = errorFamily(code);
    const lines = families.get(family) ?? [];
    lines.push(`- \`${code}\` — ${ERROR_GUIDANCE[code]}`);
    families.set(family, lines);
  }

  const sections = [...families.entries()]
    .map(([family, lines]) => `## ${family}_*\n\n${lines.join('\n')}`)
    .join('\n\n');

  return `# Error codes and what to do about them

${GENERATED_NOTE}

Every Agentship error carries \`code\`, \`message\`, \`retryable\` and usually a \`remediation\`.
Read the remediation first: it is written for you to relay. Codes are grouped by family, so
you can react to a class of failure without knowing every member.

${sections}

## Rules

- Never invent a fix that contradicts the remediation.
- \`retryable: true\` (rate limits, store outages, download failures) is the only case where
  repeating the same call unchanged is reasonable.
- A failed apply never needs cleaning up by hand: call \`agentship_resume\`, which re-reads the
  journal and the store and continues from the real state.
`;
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content);
  console.log(`wrote ${path}`);
}

export function generatedFiles(): Record<string, string> {
  const stores = storesMarkdown();
  return {
    [join(SKILLS_DIR, 'agentship-publish/references/stores.md')]: stores,
    [join(SKILLS_DIR, 'agentship-first-release/references/stores.md')]: stores,
    [join(SKILLS_DIR, 'agentship-troubleshoot/references/errors.md')]: errorsMarkdown(),
  };
}

const invokedDirectly =
  process.argv[1] !== undefined && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedDirectly) {
  for (const [path, content] of Object.entries(generatedFiles())) {
    await writeIfChanged(path, content);
  }
}
